main: main.cpp
	mpic++ -w main.cpp -o /home/cesar/Resultado/exe `pkg-config --cflags --libs opencv`

clean:
	rm -f /home/cesar/Resultado/exe imagenNode1.jpg imagenNode1.jpg imagenNode2.jpg imagenNode3.jpg imagenNode4.jpg imagenNode5.jpg imagenNode6.jpg imagenNode7.jpg imagenNode8.jpg imagenNode9.jpg imagenNode10.jpg imagenNode11.jpg imagenNode12.jpg final.jpg
